language: python
python:
    - '3.6'

#command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install .

#command to run tests
script:
  - py.tests --cov sande --cov-report term-missing

after_success:
  - coveralls
